/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaDelegate.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import androidx.annotation.Nullable;
import com.facebook.react.bridge.ReadableArray;
import com.facebook.react.bridge.ReadableMap;
import com.facebook.react.uimanager.BaseViewManager;
import com.facebook.react.uimanager.BaseViewManagerDelegate;
import com.facebook.react.uimanager.LayoutShadowNode;

public class CASAdViewManagerDelegate<T extends View, U extends BaseViewManager<T, ? extends LayoutShadowNode> & CASAdViewManagerInterface<T>> extends BaseViewManagerDelegate<T, U> {
  public CASAdViewManagerDelegate(U viewManager) {
    super(viewManager);
  }
  @Override
  public void setProperty(T view, String propName, @Nullable Object value) {
    switch (propName) {
      case "sizeConfig":
        mViewManager.setSizeConfig(view, (ReadableMap) value);
        break;
      case "autoReload":
        mViewManager.setAutoReload(view, value == null ? true : (boolean) value);
        break;
      case "casId":
        mViewManager.setCasId(view, value == null ? null : (String) value);
        break;
      case "refreshInterval":
        mViewManager.setRefreshInterval(view, value == null ? 0 : ((Double) value).intValue());
        break;
      case "placement":
        mViewManager.setPlacement(view, value == null ? null : (String) value);
        break;
      default:
        super.setProperty(view, propName, value);
    }
  }

  @Override
  public void receiveCommand(T view, String commandName, @Nullable ReadableArray args) {
    switch (commandName) {
      case "loadAd":
        mViewManager.loadAd(view);
        break;
    }
  }
}
