/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaDelegate.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import androidx.annotation.Nullable;
import com.facebook.react.bridge.ColorPropConverter;
import com.facebook.react.bridge.ReadableArray;
import com.facebook.react.uimanager.BaseViewManager;
import com.facebook.react.uimanager.BaseViewManagerDelegate;
import com.facebook.react.uimanager.LayoutShadowNode;

public class CASNativeAdViewManagerDelegate<T extends View, U extends BaseViewManager<T, ? extends LayoutShadowNode> & CASNativeAdViewManagerInterface<T>> extends BaseViewManagerDelegate<T, U> {
  public CASNativeAdViewManagerDelegate(U viewManager) {
    super(viewManager);
  }
  @Override
  public void setProperty(T view, String propName, @Nullable Object value) {
    switch (propName) {
      case "instanceId":
        mViewManager.setInstanceId(view, value == null ? 0 : ((Double) value).intValue());
        break;
      case "width":
        mViewManager.setWidth(view, value == null ? Float.NaN : ((Double) value).floatValue());
        break;
      case "height":
        mViewManager.setHeight(view, value == null ? Float.NaN : ((Double) value).floatValue());
        break;
      case "usesTemplate":
        mViewManager.setUsesTemplate(view, value == null ? false : (boolean) value);
        break;
      case "backgroundColor":
        mViewManager.setBackgroundColor(view, ColorPropConverter.getColor(value, view.getContext()));
        break;
      case "primaryColor":
        mViewManager.setPrimaryColor(view, ColorPropConverter.getColor(value, view.getContext()));
        break;
      case "primaryTextColor":
        mViewManager.setPrimaryTextColor(view, ColorPropConverter.getColor(value, view.getContext()));
        break;
      case "headlineTextColor":
        mViewManager.setHeadlineTextColor(view, ColorPropConverter.getColor(value, view.getContext()));
        break;
      case "headlineFontStyle":
        mViewManager.setHeadlineFontStyle(view, value == null ? null : (String) value);
        break;
      case "secondaryTextColor":
        mViewManager.setSecondaryTextColor(view, ColorPropConverter.getColor(value, view.getContext()));
        break;
      case "secondaryFontStyle":
        mViewManager.setSecondaryFontStyle(view, value == null ? null : (String) value);
        break;
      default:
        super.setProperty(view, propName, value);
    }
  }

  @Override
  public void receiveCommand(T view, String commandName, @Nullable ReadableArray args) {
    switch (commandName) {
      case "registerAsset":
        mViewManager.registerAsset(view, args.getInt(0), args.getInt(1));
        break;
    }
  }
}
