/**
* This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
*
* Do not edit this file as changes may cause incorrect behavior and will be lost
* once the code is regenerated.
*
* @generated by codegen project: GeneratePropsJavaInterface.js
*/

package com.facebook.react.viewmanagers;

import android.view.View;
import androidx.annotation.Nullable;


public interface CASNativeAdViewManagerInterface<T extends View> {
  void setInstanceId(T view, int value);
  void setWidth(T view, float value);
  void setHeight(T view, float value);
  void setUsesTemplate(T view, boolean value);
  void setBackgroundColor(T view, @Nullable Integer value);
  void setPrimaryColor(T view, @Nullable Integer value);
  void setPrimaryTextColor(T view, @Nullable Integer value);
  void setHeadlineTextColor(T view, @Nullable Integer value);
  void setHeadlineFontStyle(T view, @Nullable String value);
  void setSecondaryTextColor(T view, @Nullable Integer value);
  void setSecondaryFontStyle(T view, @Nullable String value);
  void registerAsset(T view, int assetType, int reactTag);
}
