
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateModuleJavaSpec.js
 *
 * @nolint
 */

package com.cleveradssolutions.plugin.reactnative;

import com.facebook.proguard.annotations.DoNotStrip;
import com.facebook.react.bridge.Promise;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.ReactContextBaseJavaModule;
import com.facebook.react.bridge.ReactMethod;
import com.facebook.react.bridge.ReadableArray;
import com.facebook.react.bridge.ReadableMap;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

public abstract class NativeCASMobileAdsModuleSpec extends ReactContextBaseJavaModule {
  public static final String NAME = "CASMobileAds";

  public NativeCASMobileAdsModuleSpec(ReactApplicationContext reactContext) {
    super(reactContext);
  }

  @Override
  public @Nonnull String getName() {
    return NAME;
  }

  @ReactMethod
  @DoNotStrip
  public abstract void initialize(String casId, ReadableMap options, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void isInitialized(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void getSDKVersion(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void showConsentFlow(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void setUserId(@Nullable String identifier);

  @ReactMethod
  @DoNotStrip
  public abstract void setUserAge(double age);

  @ReactMethod
  @DoNotStrip
  public abstract void setUserGender(double gender);

  @ReactMethod
  @DoNotStrip
  public abstract void setAppContentUrl(@Nullable String contentUrl);

  @ReactMethod
  @DoNotStrip
  public abstract void setAppKeywords(ReadableArray keywords);

  @ReactMethod
  @DoNotStrip
  public abstract void setDebugLoggingEnabled(boolean enabled);

  @ReactMethod
  @DoNotStrip
  public abstract void setAdSoundsMuted(boolean muted);

  @ReactMethod
  @DoNotStrip
  public abstract void setLocationCollectionEnabled(boolean enabled);

  @ReactMethod
  @DoNotStrip
  public abstract void setTrialAdFreeInterval(double interval);

  @ReactMethod
  @DoNotStrip
  public abstract void isInterstitialAdLoaded(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void loadInterstitialAd();

  @ReactMethod
  @DoNotStrip
  public abstract void showInterstitialAd();

  @ReactMethod
  @DoNotStrip
  public abstract void setInterstitialPlacement(@Nullable String placement);

  @ReactMethod
  @DoNotStrip
  public abstract void setInterstitialAutoloadEnabled(boolean enabled);

  @ReactMethod
  @DoNotStrip
  public abstract void setInterstitialAutoshowEnabled(boolean enabled);

  @ReactMethod
  @DoNotStrip
  public abstract void setInterstitialMinInterval(double seconds);

  @ReactMethod
  @DoNotStrip
  public abstract void restartInterstitialInterval();

  @ReactMethod
  @DoNotStrip
  public abstract void destroyInterstitial();

  @ReactMethod
  @DoNotStrip
  public abstract void isRewardedAdLoaded(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void loadRewardedAd();

  @ReactMethod
  @DoNotStrip
  public abstract void showRewardedAd();

  @ReactMethod
  @DoNotStrip
  public abstract void setRewardedPlacement(@Nullable String placement);

  @ReactMethod
  @DoNotStrip
  public abstract void setRewardedAutoloadEnabled(boolean enabled);

  @ReactMethod
  @DoNotStrip
  public abstract void setRewardedSSVerificationData(@Nullable String data);

  @ReactMethod
  @DoNotStrip
  public abstract void destroyRewarded();

  @ReactMethod
  @DoNotStrip
  public abstract void isAppOpenAdLoaded(Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void loadAppOpenAd();

  @ReactMethod
  @DoNotStrip
  public abstract void showAppOpenAd();

  @ReactMethod
  @DoNotStrip
  public abstract void setAppOpenPlacement(@Nullable String placement);

  @ReactMethod
  @DoNotStrip
  public abstract void setAppOpenAutoloadEnabled(boolean enabled);

  @ReactMethod
  @DoNotStrip
  public abstract void setAppOpenAutoshowEnabled(boolean enabled);

  @ReactMethod
  @DoNotStrip
  public abstract void destroyAppOpen();

  @ReactMethod
  @DoNotStrip
  public abstract void loadNativeAd(double maxNumberOfAds);

  @ReactMethod
  @DoNotStrip
  public abstract void setNativeMutedEnabled(boolean enabled);

  @ReactMethod
  @DoNotStrip
  public abstract void setNativeAdChoicesPlacement(double adChoicesPlacement);

  @ReactMethod
  @DoNotStrip
  public abstract void setNativePlacement(@Nullable String placement);

  @ReactMethod
  @DoNotStrip
  public abstract void destroyNative(double instanceId);

  @ReactMethod
  @DoNotStrip
  public abstract void isNativeExpired(double instanceId, Promise promise);

  @ReactMethod
  @DoNotStrip
  public abstract void addListener(String eventName);

  @ReactMethod
  @DoNotStrip
  public abstract void removeListeners(double count);
}
