[libraries]
#cas-families='com.cleveradssolutions:cas-families:3.2.5'
cas-sdk='com.cleveradssolutions:cas-sdk:3.2.5'
cas-google='com.cleveradssolutions:google:22.3.0.0'
cas-unity='com.cleveradssolutions:unity:4.8.0.0'
cas-ironsource='com.cleveradssolutions:ironsource:7.5.0.0'
cas-adcolony='com.cleveradssolutions:adcolony:4.8.0.12'
cas-kidoz='com.cleveradssolutions:kidoz:8.9.9.0'
#cas-superawesome='com.cleveradssolutions:superawesome:9.1.0.2'
cas-vungle='com.cleveradssolutions:vungle:6.12.1.7'
cas-inmobi='com.cleveradssolutions:inmobi:10.1.4.4'
cas-chartboost='com.cleveradssolutions:chartboost:9.4.1.0'
cas-fyber='com.cleveradssolutions:fyber:8.2.3.4'
cas-facebook='com.cleveradssolutions:facebook:6.16.0.0'
cas-mintegral='com.cleveradssolutions:mintegral:16.4.91.0'
cas-applovin='com.cleveradssolutions:applovin:11.11.3.0'
cas-mytarget='com.cleveradssolutions:mytarget:5.17.0.1'
cas-yandex='com.cleveradssolutions:yandex:25.10.0.0'
cas-pangle='com.cleveradssolutions:pangle:5.3.0.5'
cas-promo='com.cleveradssolutions:cas-promo:3.2.5'
